copy FxAztec.FXSYS\Synonym.FxAztec.FXSYS.usp_TableToHTML.sql /b DeployChanges.sql
copy DeployChanges.sql + FxAztec.SUPPLIEREDI\Procedure.FxAztec.SUPPLIEREDI.usp_Process.sql /b DeployChanges.sql
copy DeployChanges.sql + FxAztec.SUPPLIEREDI\Procedure.FxAztec.SUPPLIEREDI.usp_Receiver_byReceiverObjectList.sql /b DeployChanges.sql
copy DeployChanges.sql + FxAztec.SUPPLIEREDI\Procedure.FxAztec.SUPPLIEREDI.usp_Waupaca_CancelEdiShipper.sql /b DeployChanges.sql
copy DeployChanges.sql + FxAztec.SUPPLIEREDI\Procedure.FxAztec.SUPPLIEREDI.usp_Waupaca_CancelEdiShipperLine.sql /b DeployChanges.sql
copy DeployChanges.sql + FxAztec.SUPPLIEREDI\Procedure.FxAztec.SUPPLIEREDI.usp_Waupaca_GetReceiverDetails_byRawDocumentGuidList.sql /b DeployChanges.sql
copy DeployChanges.sql + FxAztec.SUPPLIEREDI\Procedure.FxAztec.SUPPLIEREDI.usp_Waupaca_GetShipNoticeAlerts_byRawDocumentGuidList.sql /b DeployChanges.sql
copy DeployChanges.sql + FxAztec.SUPPLIEREDI\Procedure.FxAztec.SUPPLIEREDI.usp_Waupaca_GetShipNoticeLines_byRawDocumentGuidList.sql /b DeployChanges.sql
copy DeployChanges.sql + FxAztec.SUPPLIEREDI\Procedure.FxAztec.SUPPLIEREDI.usp_Waupaca_GetShipNotices.sql /b DeployChanges.sql
copy DeployChanges.sql + FxAztec.SUPPLIEREDI\Procedure.FxAztec.SUPPLIEREDI.usp_Waupaca_ProcessEdiShipper.sql /b DeployChanges.sql
copy DeployChanges.sql + FxAztec.SUPPLIEREDI\Procedure.FxAztec.SUPPLIEREDI.usp_Waupaca_ReceiverDetail_SetAsnGuid.sql /b DeployChanges.sql
copy DeployChanges.sql + FxAztec.SUPPLIEREDI\Procedure.FxAztec.SUPPLIEREDI.usp_Waupaca_RestoreEdiShipper.sql /b DeployChanges.sql
copy DeployChanges.sql + FxAztec.SUPPLIEREDI\Procedure.FxAztec.SUPPLIEREDI.usp_Waupaca_RestoreEdiShipperLine.sql /b DeployChanges.sql
copy DeployChanges.sql + FxAztec.SUPPLIEREDI\Procedure.FxAztec.SUPPLIEREDI.usp_Waupaca_SaveSupplierPart.sql /b DeployChanges.sql
copy DeployChanges.sql + FxAztec.SUPPLIEREDI\Procedure.FxAztec.SUPPLIEREDI.usp_Waupaca_UndoProcessEdiShipper.sql /b DeployChanges.sql
copy DeployChanges.sql + FxAztec.SUPPLIEREDI\View.FxAztec.SUPPLIEREDI.WaupacaShipNoticeAlerts.sql /b DeployChanges.sql
copy DeployChanges.sql + FxAztec.SUPPLIEREDI\View.FxAztec.SUPPLIEREDI.WaupacaShipNoticeLines.sql /b DeployChanges.sql
copy DeployChanges.sql + FxAztec.SUPPLIEREDI\View.FxAztec.SUPPLIEREDI.WaupacaShipNotices.sql /b DeployChanges.sql
copy DeployChanges.sql + FxEDI.FXSYS\Synonym.FxEDI.FXSYS.Rows.sql /b DeployChanges.sql
copy DeployChanges.sql + FxSYS\Procedure.FxSYS.dbo.usp_EmailError.sql /b DeployChanges.sql
copy DeployChanges.sql + FxSYS\Procedure.FxSYS.dbo.usp_TableToHTML.sql /b DeployChanges.sql
copy DeployChanges.sql + FxSYS\ScalarFunction.FxSYS.dbo.fn_CamelCase.sql /b DeployChanges.sql